### ISSUE TITLE
add global flags to suggestion list

### ISSUE THREAD

**Issue by karimra** [karimra/gnmic#155]
Should we add global flags to suggestions list in these 2 cases ?
- suggesting commands ( get, set, ...), the full list will have the commands first then the global flags
- suggesting local flags, the full list will have the local flags first then the global flags

Should this be the default behavior or enabled via a flag of prompt command ?

**Comment by neoul** [comment]
@karimra I think there are a lot of the global flags. And I think that can be configured at starting prompt. So, I think that needs to be hidden for simpleness.

**Comment by karimra** [comment]
I agree that there are too many global flags. It can be too much to show at once
I think we can find a compromise like:
- suggest commands then global flags when in root level. Because right now getting global flags in root level is kind of hidden ( needs a `-` )
- use a new prompt flag `suggest-all-flags` to enable suggesting global flags under subcommands.

I'm open to suggestions, but I think this should be configurable.

**Comment by hellt** [comment]
we've discussed this today and so far have converged on the following

1) as the prompt starts, the suggestions immediately appear and show top level commands AND global flags
2) once the subcommand is typed in, only local flags suggested to it

**Comment by karimra** [comment]
1. is already addressed in #156
