### ISSUE TITLE
CompletionOnDown() option causes a crash if history exists.

### ISSUE THREAD

**Issue by neoul** [karimra/gnmic#177]
I think we need to disable  `goprompt.OptionCompletionOnDown()` option upon the start of the prompt mode.

go-prompt history uses the up/down key for its history index exploration.
When we enable `goprompt.OptionCompletionOnDown()`, it seems to cause a crash.
Because, down key is used in both the history and the completion logic of go-prompt.
It doesn't happen if `goprompt.OptionCompletionOnDown()` is disabled or disable `goprompt.OptionHistory(promptHistory)`.

So, we need to disable it temporarily.
I think you can reproduce it if you push up and down keys quickly when there are history commands and suggestion exists.

```bash
gnmic> capabilitiespanic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/c-bata/go-prompt.(*CompletionManager).GetSelectedSuggestion(0xc0003eb540, 0xc000044340, 0xc0003eb540, 0x13, 0x0, 0x1)
	/home/neoul/go/pkg/mod/github.com/c-bata/go-prompt@v0.2.5/completion.go:51 +0x104
github.com/c-bata/go-prompt.(*Render).Render(0xc0005d8410, 0xc000044340, 0xc0003eb540)
	/home/neoul/go/pkg/mod/github.com/c-bata/go-prompt@v0.2.5/render.go:207 +0x3d7
github.com/c-bata/go-prompt.(*Prompt).Run(0xc000469b00)
	/home/neoul/go/pkg/mod/github.com/c-bata/go-prompt@v0.2.5/prompt.go:100 +0x740
github.com/karimra/gnmic/cmd.cmdPrompt.Run(0x1adfec0, 0xc000468fc0, 0x12, 0x12)
	/home/neoul/go/src/github.com/neoul/gnmic/cmd/prompt.go:425 +0xf2
github.com/karimra/gnmic/cmd.ExecutePrompt()
	/home/neoul/go/src/github.com/neoul/gnmic/cmd/prompt.go:392 +0x4d8
github.com/karimra/gnmic/cmd.Execute()
	/home/neoul/go/src/github.com/neoul/gnmic/cmd/root.go:143 +0x4d
main.main()
	/home/neoul/go/src/github.com/neoul/gnmic/main.go:29 +0x3a
neoul@neoul-note:~/go/src/github.com/neoul/gnmic$
```

**Comment by karimra** [comment]
Hi Neoul,

Thanks for catching this, I'm able to reproduce it as well.
Seems like a bug in go-prompt, I will open an issue there as well.
