### ISSUE TITLE
suggestion list gets messed with Nokia modules

### ISSUE THREAD

**Issue by hellt** [karimra/gnmic#182]
Hi @karimra @neoul 
when I launch the prompt mode with [Nokia modules](https://github.com/nokia/7x50_YangModels/tree/master/latest_sros_19.10) in use like this

```
gnmic --insecure --username admin --password admin --address 10.1.0.11 --file ~/7x50_YangModels/YANG/nokia-combined/nokia-conf-combined.yang --dir ~/7x50_YangModels/YANG prompt
```

the suggestions for paths mess up when I navigate thru them, the next element selected is not the one that I see in the suggestion box, the same is for the previous element.

This animation shows it:
![CleanShot 2020-10-19 at 18 30 40](https://user-images.githubusercontent.com/5679861/96480234-46ca5380-123a-11eb-935a-1ec808571b13.gif)

the issue is not Nokia specific, the same behaviour I see with OpenConfig models:

```
./gnmic --file ~/public/release/models/ --dir ~/public/third_party prompt
```

**Comment by hellt** [comment]
I checked if the autocompletion-on-down has any effect - it doesn't

**Comment by karimra** [comment]
You mean the list is out of order? 
I have seen it before, looks like the suggestion list gets reordered after every suggestion is selected

**Comment by hellt** [comment]
Yes, it looks like whenever a selection is made, the next time you make it
- the list gets reordered
That leads to a situation when the item you see above or below the current
selection is not the one that will get selected on arrow up/down
