### ISSUE TITLE
Installing code on Big Sur doesn't seem to do anything

### ISSUE THREAD

**Issue by flyerhawk** [karimra/gnmic#221]
❯ curl -sL https://github.com/karimra/gnmic/raw/master/install.sh | sudo bash
Downloading https://github.com/karimra/gnmic/releases/download/v0.4.3/gnmic_0.4.3_darwin_x86_64.tar.gz
Preparing to install gnmic 0.4.3 into /usr/local/bin
gnmic installed into /usr/local/bin/gnmic
bash: line 173:  6287 Killed: 9               $GNMIC_INSTALL_DIR/$BINARY_NAME version

When I run the command I always get this..

[1]    6356 killed     gnmic
╭─ ~/Downloads/junos-qfx ▓▒░································································································░▒▓ KILL ✘  at 23:44:31 
╰─

**Comment by karimra** [comment]
Hi,

gnmic was not tested on Big Sur yet.
Is the system Intel-based or Apple Silicon ?

**Comment by hellt** [comment]
Hi @flyerhawk 
we seemed to have found the reason for this in one of the compression utilities we use to shrink gnmic size
We will have a fix for this in the next version

For now, you can clone the project and build it locally

**Comment by karimra** [comment]
can you give it a try with the last release? v0.5.0

**Comment by flyerhawk** [comment]
That seems to have fixed the issue!  Thanks!   FTR, I am using an intel based iMac.

**Comment by hellt** [comment]
thanks for reporting the issue. Glad it's been an easy fix =)
