### ISSUE TITLE
config file - qos

### ISSUE THREAD

**Issue by DefunctExodus** [karimra/gnmic#228]
I seem to be having issues with qos being set when using a config file regardless of if the value is set to 0 or not set at all

version
```
gnmic version
version : 0.5.0
 commit : 7b8095d
   date : 2020-11-25T11:02:56Z
 gitURL : https://github.com/karimra/gnmic
   docs : https://gnmic.kmrd.dev
```
here is the debug output

```
subscriptions: map[component:{
"name":"component",
"paths":["/components/component/"],
"mode":"stream",
"stream-mode":"sample",
"encoding":"json",
"qos":0,
"sample-interval":10000000000,
"heartbeat-interval":0}]
```
```
sending gNMI SubscribeRequest: subscribe='subscribe:{
subscription:{
  path:{
    elem:{
      name:"components"
     } 
    elem:{
      name:"component"
     }
}
mode:SAMPLE sample_interval:10000000000} 
qos:{}}',
mode='STREAM', 
encoding='JSON', to XXXXX
```

```target 'XXXXX', subscription component rcv error: rpc error: code = Unimplemented desc = Qos not supported```

This only happens when using a config file (tried toml,yml), when run through the CLI without a config file it works, so It seems like it's an issue with the config render from the file

**Comment by karimra** [comment]
Thanks for reporting this, I see the same behavior.
It will get fixed in the next version v0.5.1 (hopefully this week)

**Comment by hellt** [comment]
@DefunctExodus take for a spin the new 0.5.1 version. It had been fixed there 
Thanks for bringing this to our attention 👍

**Comment by DefunctExodus** [comment]
@hellt 
Missed this notification, sorry

It works perfectly. Thanks for getting that fix in, this is an amazing app!
