### ISSUE TITLE
SIGINT / Ctrl+C sometimes doesn't stop subscribe output early

### ISSUE THREAD

**Issue by colinmcintosh** [karimra/gnmic#236]
Hi, I'm sometimes encountering an issue with _gnmic_ where `Ctrl+C` doesn't interrupt the subscribe output and _gnmic_ will continue until no more messages are buffered before the program exits; this leads to the _gnmic_ process needing to be killed in order to stop the execution early. I would expect that mashing `Ctrl+C` or sending an interrupt signal would stop the program and exit.

Wondering if anyone else has experienced this or knows of a fix already? I took a peek through the signal handler code but wasn't able to make a fix that consistently resulted in _gnmic_ exiting when `Ctrl+C` is pressed. I did notice that for me passing the `--debug` flag to _gnmic_ will cause it to exit quickly with an interrupt but wasn't able to link that to a specific code path that was causing the issue.

**Comment by karimra** [comment]
Hi, I did notice the same and was not able to find a better Ctrl+C handling behavior.
If anyone has a fix or an enhancement they are more than welcome to create a PR

**Comment by colinmcintosh** [comment]
I think I figured this out but a second set of eyes would be great to confirm.

From what I'm seeing the file Output sends all writes immediately to File.Write() which will block until output is written regardless of context.Context being "done". A submitted a PR that changes the behavior to limit calls to File.Write() to a ConcurrencyLimit specified in file.Config. The default limit is 1000 which seemed somewhat sane based my tests pressing Ctrl+C on my laptop.

This solution seemed reasonable for getting File.Write() to honor Context.Done() but open to looking at alternatives as well if someone has a different idea.

**Comment by hellt** [comment]
thanks for your contribution @colinmcintosh 
it's been merged and gnmic 0.6.0 will have this fix in place
