### ISSUE TITLE
"gnmic promp" Display Issue

### ISSUE THREAD

**Issue by LukeCage** [karimra/gnmic#237]
Hi @hellt,

So far, gnmic seems to working but there is an inelegance in the display of "gnmic prompt" that did not exist before. After issuing a command and pressing enter, right after providing the credentials for the account and before the data is streamed, the prompt options are displayed.

This is disruptive to the display of information that is of value/importance and it interferes with the use of the screen size that is available to display the data. Never happened before.

The menu of options should not be displayed until the "gnmi prompt shell" is broken.

Luke.

**Comment by karimra** [comment]
In a the latest version of gnmic, when in prompt mode, after a subscribe command is issued, the prompt is given back early to allow using other commands ( creating multiple subscriptions ).

What is happening in your case is that multiple data sources are printing to the terminal at the same time, logs, subscription output and the prompt.

You can try disabling --debug or log to a file with --log-file.
If you are using gnmic to get the subscription output on the terminal you can consider using the subscribe command outside of the prompt. The prompt will be existed on the next CTRL+C to stop the subscription anyways.

PS: the prompt mode is still in its early days ( actually, gnmic as well ), so yes it has a few rough edges.

**Comment by hellt** [comment]
@LukeCage did you try prompt without debug/log options?
