### ISSUE TITLE
configure subscriptions using a file

### ISSUE THREAD

**Issue by 112shaggy** [karimra/gnmic#240]
Hi!

First of all, thanks for the work done on this. I really appreciate it.

Regarding the issue I'm encountering, I'm trying to configure subscriptions over a file and I'm using your example as a base (https://github.com/karimra/gnmic/blob/master/config.json).
Unfortunately, I'm not being able to use the file because, whenever I try to use it, the help menu shows up, as you can see below.

Linux:~$ gnmic --config ./test.json
run gnmi rpcs from the terminal (https://gnmic.kmrd.dev)

Usage:
  gnmic [command]

Available Commands:
  capabilities query targets gnmi capabilities
  get          run gnmi get on targets
  help         Help about any command
  listen       listens for telemetry dialout updates from the node
  path         generate gnmi or xpath style from yang file
  prompt       enter the interactive gnmic prompt mode
  set          run gnmi set on targets
  subscribe    subscribe to gnmi updates on targets
  version      show gnmic version

Flags:
  -a, --address strings             comma separated gnmi targets addresses
      --config string               config file (default is $HOME/gnmic.yaml)
  -d, --debug                       debug mode
  -e, --encoding string             one of ["json" "bytes" "proto" "ascii" "json_ietf"]. Case insensitive (default "json")
      --format string               output format, one of: ["json" "protojson" "prototext" "event" "proto"]
  -h, --help                        help for gnmic
      --insecure                    insecure connection
      --log                         show log messages in stderr
      --log-file string             log file path
      --max-msg-size int            max grpc msg size (default 536870912)
      --no-prefix                   do not add [ip:port] prefix to print output in case of multiple targets
  -p, --password string             password
      --port string                 gRPC port (default "57400")
      --print-request               print request as well as the response(s)
      --prometheus-address string   prometheus server address
      --proxy-from-env              use proxy from environment
      --retry duration              retry timer for RPCs (default 10s)
      --skip-verify                 skip verify tls connection
      --timeout duration            grpc timeout, valid formats: 10s, 1m30s, 1h (default 10s)
      --tls-ca string               tls certificate authority
      --tls-cert string             tls certificate
      --tls-key string              tls key
  -u, --username string             username

Use "gnmic [command] --help" for more information about a command.

Basically it's not detecting any command but I have subscriptions created on the file, as you can see below.

{
    "username": "admin",
    "password": "admin",
    "port": 57400,
    "timeout": "5s",
    "skip-verify": true,
	"insecure": true
    "targets": {
        "x.x.x.x": {
            "username": "admin",
            "password": "admin",
            "insecure": true,
            "subscriptions": [
                "sub1"
            ],
            "outputs": [
                "output1"
            ]
        }
    },
    "subscriptions": {
        "sub1": {
            "paths": [
                "/state/port[port-id=*]/statistics/in-packets"
            ],
            "stream-mode": "sample",
			"sample-interval": "5s"
        }
    },
    "outputs": {
        "output1": {
            "type": "file",
            "file-type": "test.log"
        },
	}
}

This is probably my mistake but so far I wasn't able to surpass it and I was wondering if you have any ideas.

**Comment by hellt** [comment]
Hi @112shaggy!

The configuration file will not start the defined subscriptions for you, you need to command that. Meaning that in you case the command to subscribe to the defined subscription will be as simple as:

```
gnmic --config ./test.json subscribe
```

**Comment by 112shaggy** [comment]
Hi hellt,

Thanks very much!

I didn't realised that we needed to add the subscribe command but it makes total sense.

Unfortunately, I got another error.
Linux:~$ gnmic --config ./test.json subscribe
**Error: failed getting targets config: unexpected targets format, got: <nil>**
 
What am I missing in the targets?

**Comment by hellt** [comment]
If I read your pasted config correctly, you didn't specify addresses of the
network elements to which you want to initiate the gnmi connection

https://gnmic.kmrd.dev/advanced/multi_target/

**Comment by karimra** [comment]
hi @112shaggy , the file is missing a comma after `"insecure: true"` and before `"targets": {...`

there is also an extra comma after `test.log}` here `"file-type": "test.log"
},`

**Comment by 112shaggy** [comment]
Thanks for the help!

Like you said, I had some config typos and was missing the address of the node.
Additionally, I had "file-type" followed by the filename, not the type. I changed it and it started to work!

I'm pretty new to this so I appreciate the help.

**Comment by hellt** [comment]
Great to here that it helped
I'm closing this issue then, and if anything comes along your way which you don't fully understand, you can open a discussion on this repo
