### ISSUE TITLE
Unable to retrieve configs from junos device

### ISSUE THREAD

**Issue by sandeepabvp** [karimra/gnmic#303]
I have used below command for junos, its working for cisco router with IOSXR

gnmic -a ip:50051 --insecure -u uname -p pwd get --path "junos-rpc-lldp:" -e json_ietf --log
it is printing everything
[
  {
    "timestamp": 1612984816,
    "time": "1969-12-31T17:00:01.612984816-07:00",
    "updates": [
      {
        "Path": "junos-rpc-lldp:",
        "values": {
          "": {
            "configuration": {
              "@": {
                "junos:commit-localtime": "2021-02-09 17:10:41 UTC",
                "junos:commit-seconds": "1612890641",
                "junos:commit-user": "ansible",
                "xmlns": "http://xml.juniper.net/xnm/1.1/xnm"
              },
              "chassis": {
                "aggregated-devices": {
                  "ethernet": {
                    "device-count": 64
                  },
                  "maximum-links": 64
                },
............ more output from router

i am not able to access anything inside the path .
if i give anything in path after: like "configuration/chassis".. it gives error below
[gnmic] 2021/02/10 12:29:18.829349 failed sending GetRequest to ip:50051: failed sending GetRequest to 'ip:50051': rpc error: code = Unknown desc = Error in retrieval for the given config path

i tried to use the path using prompt with following command after gnmic --file junos/rpc --dir common prompt
-a ip:50051 --insecure -u uname -p pwd -e json_ietf get --model junos-rpc-lldp --path /get-aaa-accounting-status --log

it gives the same error as above

Appreciate you help

**Comment by hellt** [comment]
Hi @sandeepabvp 
if you have a Juniper SE that you can forward that question that would be good. because the reason is that juniper state information is modelled with RPCs, not state leafs. This causes this error, as the state data can't be accessed by a path.

I've asked around, maybe someone from Juniper will share the way how it is supposed to be done

**Comment by hellt** [comment]
check this answer
https://twitter.com/door7302/status/1359836593192861696

you should use sensors explorer to find the paths that you can subscribe (GET is not supported by Junos it seems)

example:

```
gnmic -a clab-vmx-vmx -u admin -p admin@123 --insecure sub -e proto --path "/interfaces/interface/state/counters/in-octets" --mode once
```

**Comment by amanand** [comment]
I am not sure about the semantics of gnmic, but Juniper does support GNMI GET/SET/Subscribe RPCs
Sample o/p of a gnmi get using an internal tool:

type: CONFIG
encoding: JSON_IETF

--------------------------------------------------------
notification {
  timestamp: 1613070239
  update {
    path {
      origin: "juniper"
      elem {
        name: "chassis"
      }
    }
    val {
      json_ietf_val: "{\"memory-enhanced\": [null], \"synchronization\": {\"loop-prevention\": \"master-side\"}}"
    }
  }
}

**Comment by hellt** [comment]
Hi @amanand 
Thank you for taking time to comment, appreciate.
I failed to find any documentation on how to construct gNMI compatible paths, but with your example it is now clear.

The trick is to derive the origin that you guys seem to use to scope the YANG model. You have `juniper` in your example, and I don't believe there are YANG models available on Juniper github that discloses that prefix?

Using the sensor explorer I can see that `origin: "juniper"` maps to junos directory of sensors:
![image](https://user-images.githubusercontent.com/5679861/107690623-a3022900-6caa-11eb-8633-97df1901dd2c.png)
although the path provided within the sensor explorer doesn't really match. Which is fine if you know the "hidden" rules.

for the sake of completeness, here is the `gnmic` command that matches your example

```
❯ gnmic -a clab-vmx-vmx -u admin -p admin@123 --insecure get -e json_ietf --path "juniper:chassis"
Get Response:
[
  {
    "timestamp": 1613072631,
    "time": "1970-01-01T00:00:01.613072631Z",
    "updates": [
      {
        "Path": "juniper:chassis",
        "values": {
          "chassis": {
            "fpc": [
              {
                "name": 0,
                "pic": [
                  {
                    "name": 0,
                    "number-of-ports": 96
                  }
                ]
              }
            ]
          }
        }
      }
    ]
  }
]


Now I wonder, how can I access with **gNMI Get** the `interfaces` container? Which origin should I use?

**Comment by amanand** [comment]
Did you can try both openconfig:interfaces and juniper:interfaces?

**Comment by hellt** [comment]
@amanand thank, using `juniper` origin for `interfaces` worked, whereas the former variant didn't

```
❯ gnmic -a clab-vmx-vmx -u admin -p admin@123 --insecure get -e json_ietf --path "juniper:interfaces/interface"
Get Response:
[
  {
    "timestamp": 1613073244,
    "time": "1970-01-01T00:00:01.613073244Z",
    "updates": [
      {
        "Path": "juniper:interfaces/interface",
        "values": {
          "interfaces/interface": [
            {
              "name": "fxp0",
              "unit": [
                {
                  "family": {
                    "inet": {
                      "address": [
                        {
                          "name": "10.0.0.15/24"
                        }
                      ]
                    }
                  },
                  "name": 0
                }
              ]
            }
          ]
        }
      }
    ]
  }
]
```

A pity that the origin is kind of a guess-game, but at least we see that Get is working. Thank you!

**Comment by amanand** [comment]
Thats probably because you don't have openconfig schema based interface configurations. Can you try to SET something using openconfig:interfaces and then try to fetch it using GET with the path set as openconfig:interfaces?

**Comment by sandeepabvp** [comment]
Thank you @hellt & @amanand 
its just a word before the path and i have been struggling with it for 2 days. Its working for me on native models i will try on openconfig as well and other commands like set/sub too

**Comment by hellt** [comment]
> Thats probably because you don't have openconfig schema based interface configurations.

I see, the native config is not translated to OC like it does on XR. That explains.

What is not clear is where does `juniper` origin come from. It is clearly used to scope the YANG model that is being used to retrieve the data, but I failed to find such a YANG model

**Comment by sandeepabvp** [comment]
Hi @hellt 
can you please provide the link of the tree view which you are displaying

**Comment by hellt** [comment]
@sandeepabvp https://apps.juniper.net/telemetry-explorer/explore?software=Junos%20OS&release=20.2R1&moduleId=All&tagId=100508&tagName=junos

**Comment by sandeepabvp** [comment]
> @sandeepabvp https://apps.juniper.net/telemetry-explorer/explore?software=Junos%20OS&release=20.2R1&moduleId=All&tagId=100508&tagName=junos

Thank you
