### ISSUE TITLE
Quiet Output (print only Value)

### ISSUE THREAD

**Issue by mike-albano** [karimra/gnmic#316]
Firstly, great utility.

Is there a current method to print only the Value of a Get or SubscribeRequest response?

For example, print (or otherwise output) only the int (2 in this case) of the following GetRequest?
```
gnmic -a prod-ap.mikealbano.com:8080 -u admin -p admin get --skip-verify --path /access-points/access-point[hostname=ap1.example.net]/radios/radio[id=0][operating-frequency=FREQ_5GHZ]/state/total-channel-utilization
Get Response:
[
  {
    "timestamp": 1614117132817888160,
    "time": "2021-02-23T14:52:12.81788816-07:00",
    "updates": [
      {
        "Path": "access-points/access-point[hostname=ap1.example.net]/radios/radio[operating-frequency=FREQ_5GHZ][id=0]/state/total-channel-utilization",
        "values": {
          "access-points/access-point/radios/radio/state/total-channel-utilization": 2
        }
      }
    ]
  }
]
```
Easy enough to key into the response JSON, but sometimes handy for debugging if only the value of the "values" is printed.

**Comment by hellt** [comment]
Hi @mike-albano ,
Currently it's envisioned that users will use something like jq to programmatically get the value directly.

The jq expression for the case of a single value in the response will be universal and thus can be used uniformly in every such request. Will that work for your case?

Personally I think making a flag that would print only the value is likely not worth it, as a response might have many key-value pairs in it's body.

**Comment by karimra** [comment]
Hi, 

Try this jq filter: ` $YOUR_GNMIC_CMD | jq '.[].updates[].values | ."$VALUE_NAME"'`
in your case: `VALUE_NAME=access-points/access-point/radios/radio/state/total-channel-utilization`
note the `''` around the jq filter

**Comment by mike-albano** [comment]
@hellt true this is only useful where an xpath is supplied down to a single leaf-node; eg one Value is returned.

@karimra jq is handy, but "Get Response:\n" is also included, so the response is not strictly JSON. Perhaps this was added after [this](https://netdevops.me/2020/gnmic-gnmi-cli-client-and-collector/) was written (see "Automation friendly output"). 

subscribe does not print the "Get Response:\n" and jq works perfectly well for that (thanks for the tip).
```
gnmic -a prod-ap.mikealbano.com:8080 -u admin -p admin sub --skip-verify --path access-points/access-point[hostname=ap1.example.net]/radios/radio[id=0][operating-frequency=FREQ_5GHZ]/state/total-channel-utilization --stream-mode sample --sample-interval 2s --updates-only | jq '.updates[].values."access-points/access-point/radios/radio/state/total-channel-utilization"'
1
2
2
...
```
So perhaps removal of the printing of "Get Response:" is all that's needed to utilize the GetRequest output programmatically (either by consuming the json/dict/map that's returned or stdout + jq) as originally intended in that [article](https://netdevops.me/2020/gnmic-gnmi-cli-client-and-collector/)?

Wild guess on [the source](https://github.com/karimra/gnmic/blob/06c8ffd113cc01f6b4ace0b0a44a1736d35236a2/app/get.go#L86).

**Comment by karimra** [comment]
@mike-albano 
"Get Response:\n" is printed to stderr, while the actual output is on stdout, maybe redirect stderr to /dev/null ?
`$YOUR_GNMIC_CMD 2>/dev/null | jq '.[].updates[].values | ."$VALUE_NAME"'`

I agree that the command is getting lengthy :)

**Comment by mike-albano** [comment]
Good point on the stderr.
"I think a compromise could be printing "Get Response" only if the Request is printed as well"

Yes, I think this is a good suggestion as it allows a consumer to programmatically load the GetResponse; also aligns it with how a "SubscribeResponse" is printed.

**Comment by hellt** [comment]
Hi @mike-albano,
because "Get Response" is sent to stderr by default, it won't mess with piping to `jq`, as the pipe will by default work with stdout outputs

![image](https://user-images.githubusercontent.com/5679861/108961711-07909100-7678-11eb-9494-7bc0f566b5a5.png)

Also this universal `jq` will get you the you the value without knowing a key:

```
jq '.[].updates[].values|to_entries[].value'
```

**Comment by mike-albano** [comment]
Yep, understood. The delineation of stderr and stdout makes programatic consumption possible as well (eg consume only stdout).

PR #317 aligns the behavior b/w Get and Sub; so still seems appropriate, but up to the author. Thanks for the tips, glad to see the continual development on utilities like this.

**Comment by mike-albano** [comment]
Yep; tested & looks good to me.
Thanks!
