### ISSUE TITLE
Kafka: Support SASL

### ISSUE THREAD

**Issue by gl** [karimra/gnmic#333]
The code doesn't seem to support configuring access to Kafka with SASL/User/Pwd, would it be possible to add this feature ?

**Comment by karimra** [comment]
yes, will look into it.

**Comment by karimra** [comment]
@gl, 
I added SASL PLAIN in #336 and tested it.
I also added (at least tried) SASL SCRAM and Oauth mechanisms but haven't tested them, 
I'm having hard times setting up a kafka cluster with those mechanisms.

I was wondering which mechanism you were interested in?

Current PR, adds SAL to kafka output, not yet to input.

**Comment by gl** [comment]
Great thanks ! I'll give it a try on Monday. I need SASL/Plain so I'm good with it.

**Comment by karimra** [comment]
@gl, the PR was merged and is part of the latest release v0.9.0, appreciate if you could give it a try when you have time.

**Comment by karimra** [comment]
closing due to no response, feel free to reopen if the PR did not meet your request.
