### ISSUE TITLE
config file not found

### ISSUE THREAD

**Issue by dspky35** [karimra/gnmic#343]
The documentation leads me to believe that .gnmic.yaml in $PWD would be found automatically, but I am not seeing that. I have to use the config flag to have it read.

What am I doing wrong?

cl@cl:$ echo $HOME
/home/cl
cl@cl:$ pwd
/home/cl
cl@cl:$ cat .gnmic.yaml
username: admin
password: admin
skip-verify: true
cl@cl:$ gnmic capabilities -a 10.122.52.68:50051
username:
^C
received signal 'interrupt'. terminating...

cl@cl:$ gnmic capabilities -a 10.122.52.68:50051 --config .gnmic.yaml
Capabilities Response:
gNMI version: 0.5.0
supported models:
....snipped.....
cl@cl:$

cl@cl:~$ gnmic version
version : 0.7.0
commit : dcbe8d3
date : 2021-01-28T01:58:29Z
gitURL : https://github.com/karimra/gnmic
docs : https://gnmic.kmrd.dev

I am using Ubuntu 20.04 running natively in WSL2.

**Comment by hellt** [comment]
Please consider upgrading (`gnmic version upgrade`)
The change to .gnmic.yml has been added in 0.8.0+

**Comment by dspky35** [comment]
Thank you, that worked!
