### ISSUE TITLE
gNMI Capabilities RPC does not display output in gNMIc v0.9.1

### ISSUE THREAD

**Issue by daniel-gonzalez-sanchez** [karimra/gnmic#358]
Hi everyone,

I was playing around with RPC operations in the latest version of the gNMIc client (`v0.9.1`) with an Arista cEOS router configured with the gNMI management API, when I discovered a problem with the `Capabilities request`. It seems that this operation does not display any output information. In the previous version of gNMIc (`v0.9.0`) this problem did not occur.

Many thanks in advance!

Daniel

**Comment by karimra** [comment]
Hi, 

Thanks for reporting this.
It should be solved in v0.10.0, can you please give it a try?

Thanks

**Comment by daniel-gonzalez-sanchez** [comment]
Thank you very much for the quick answer and for the solution. I'll check it again when the next release comes out.

**Comment by karimra** [comment]
v0.10.0 is just out, you can upgrade with`gnmic version upgrade` or `bash -c "$(curl -sL https://get-gnmic.kmrd.dev)"`

**Comment by daniel-gonzalez-sanchez** [comment]
I have just checked with the `v0.10.0` version and the Capabilities request is working fine. Many thanks!
