### ISSUE TITLE
Allow stdin to be passed as update value

### ISSUE THREAD

**Issue by jbemmel** [karimra/gnmic#369]
gnmic currently expects a filename for --update-file, and it can only be .json or .yaml

One can work around this using a temporary file:
```
temp_file=$(mktemp --suffix=.json); cat ethernet-1_1.json > $temp_file; gnmic -a 172.20.20.2:57400 -u admin -p admin --skip-verify -e json_ietf set  --update-path /interface[name=ethernet-1/1] --update-file $temp_file; rm -f $temp_file
```

but ideally, this would work too:
echo "<some JSON/YAML heredoc>" | gnmic -a 172.20.20.2:57400 -u admin -p admin --skip-verify -e json_ietf set  --update-path /interface[name=ethernet-1/1] --update-file -

Perhaps --update-stdin=json or --update-stdin=yaml?

**Comment by karimra** [comment]
#370 adds the following: 
- support for files without an extension, gnmic will "guess" the type of file if there is no extension.
- heredoc value for flags `--update-file` and `--replace-file`
- inline json raw string as value in flags `--update`, `--replace`, `update-value` and `--replace-value`.

Meaning all of the below commands should work (example for set update only, same commands are valid with replace):

```bash
gnmic -e json_ietf set --update-path /interface[name=ethernet-1/1] --update-value '{"admin-state":"enable"}'

gnmic -e json_ietf set --update-path /interface[name=ethernet-1/1]/admin-state --update-value enable

gnmic set --update /interface[name=ethernet-1/1]:::json_ietf:::'{"admin-state":"enable"}'

echo '{"admin-state":"enable"}'  | gnmic -e json_ietf set --update-path /interface[name=ethernet-1/1] --update-file -
```
