### ISSUE TITLE
file-type: stdout doesn't create a file

### ISSUE THREAD

**Issue by arikmoshe** [karimra/gnmic#380]
file-type should be ommited to make it work.
we should fix the guide:

https://gnmic.kmrd.dev/user_guide/outputs/file_output/

this is in the guide:
    file-type: stdout # or stderr 
it should be
    file-type:  #stdout or stderr

**Comment by karimra** [comment]
Do you mean that in order to write to the file configured under `filename`, `file-type` should be omitted ?

**Comment by arikmoshe** [comment]
yes,
maybe we can just fix the documentation:

https://gnmic.kmrd.dev/user_guide/outputs/file_output/

**Comment by karimra** [comment]
I forgot to mention it here, but updated the doc page.
Please have a look.

**Comment by karimra** [comment]
closing due to no response, feel free to reopen if the PR did not meet your request.
