### ISSUE TITLE
gnmic -h does not show --path as potential parameter

### ISSUE THREAD

**Issue by slieberth** [karimra/gnmic#383]
Hello Karim,
thanks for providing gnmic, 
minor help issue - I do  not see the --path attribute, when calling gnmic -h ... 
greetings from Berlin
Stefan

$ gnmic version
version : 0.12.2
 commit : f68027f
   date : 2021-04-24T04:17:06Z
 gitURL : https://github.com/karimra/gnmic
   docs : https://gnmic.kmrd.dev

$ gnmic -h 
run gnmi rpcs from the terminal (https://gnmic.kmrd.dev)

Usage:
  gnmic [command]

Available Commands:
  capabilities query targets gnmi capabilities
  completion   generate completion script
  get          run gnmi get on targets
  getset       run gnmi get then set on targets
  help         Help about any command
  listen       listens for telemetry dialout updates from the node
  path         generate gnmi or xpath style from yang file
  prompt       enter the interactive gnmic prompt mode
  set          run gnmi set on targets
  subscribe    subscribe to gnmi updates on targets
  version      show gnmic version

Flags:
  -a, --address strings             comma separated gnmi targets addresses
      --api string                  gnmic api address
      --cluster-name string         cluster name the gnmic instance belongs to, this is used for target loadsharing via a locker (default "default-cluster")
      --config string               config file (default is $HOME/gnmic.yaml)
  -d, --debug                       debug mode
  -e, --encoding string             one of ["json" "bytes" "proto" "ascii" "json_ietf"]. Case insensitive (default "json")
      --format string               output format, one of: ["json" "protojson" "prototext" "event" "proto"]
      --gzip                        enable gzip compression on gRPC connections
  -h, --help                        help for gnmic
      --insecure                    insecure connection
      --instance-name string        gnmic instance name
      --log                         show log messages in stderr
      --log-file string             log file path
      --max-msg-size int            max grpc msg size (default 536870912)
      --no-prefix                   do not add [ip:port] prefix to print output in case of multiple targets
  -p, --password string             password
      --port string                 gRPC port (default "57400")
      --print-request               print request as well as the response(s)
      --prometheus-address string   prometheus server address
      --proto-dir stringArray       directory to look for proto files specified with --proto-file
      --proto-file stringArray      proto file(s) name(s)
      --proxy-from-env              use proxy from environment
      --retry duration              retry timer for RPCs (default 10s)
      --skip-verify                 skip verify tls connection
      --targets-file string         path to file with targets configuration
      --timeout duration            grpc timeout, valid formats: 10s, 1m30s, 1h (default 10s)
      --tls-ca string               tls certificate authority
      --tls-cert string             tls certificate
      --tls-key string              tls key
      --tls-max-version string      maximum TLS supported version, one of ["1.3" "1.2" "1.1" "1.0" "1"]
      --tls-min-version string      minimum TLS supported version, one of ["1.3" "1.2" "1.1" "1.0" "1"]
      --tls-version string          set TLS version. Overwrites --tls-min-version and --tls-max-version, one of ["1.3" "1.2" "1.1" "1.0" "1"]
  -u, --username string             username

Use "gnmic [command] --help" for more information about a command.

**Comment by karimra** [comment]
Hi Stefan,

`--path` is a local flag to `get` and `subscribe` commands. 
You can see it with `gnmic get -h` or `gnmic subscribe -h`

The `gnmic -h` shows the commands and the global flags

**Comment by slieberth** [comment]
OK, I see it, sorry, thanks for clarifcation ...

**Comment by karimra** [comment]
no problem, anytime
