### ISSUE TITLE
Issue: Gnmic Collector connects and disconnects 

### ISSUE THREAD

**Issue by dshah2012** [karimra/gnmic#396]
Hello @karimra ,

The gnmic collectors fine. But i see that intermittent issue where it disconnects and connects back to the kafka. Not sure if this is the desired behaviour of the collector. Plus while this process is ongoing if there is any new message to sent by the device to the collector does it get lost.
This is happening when subscribing to cisco device, our path is "Cisco-IOS-XR-pfi-im-cmd-oper:interfaces/interface-xr/interface" which kind of gives the larger payload of the interface and of all the interfaces one by one. But for nokia as the payloads are small i don't see this issue. 
Not sure it is the cisco device that is not sending the payload sometimes may be because of its size, or the collector is not processing ?

```
producer/leader/dummy_topic/3 state change to [retrying-1]
[kafka_output] 2021/06/02 19:48:38.218498 /home/runner/go/pkg/mod/github.com/!shopify/sarama@v1.26.4/async_producer.go:613: producer/leader/dummy_topic/3 abandoning broker 0
[kafka_output] 2021/06/02 19:48:38.318656 /home/runner/go/pkg/mod/github.com/!shopify/sarama@v1.26.4/client.go:838: client/metadata fetching metadata for [dummy_topic] from broker dummy_kafka_broker
[kafka_output] 2021/06/02 19:48:38.319721 /home/runner/go/pkg/mod/github.com/!shopify/sarama@v1.26.4/async_producer.go:586: producer/leader/dummy_topic/3 selected broker 0
[kafka_output] 2021/06/02 19:48:38.319741 /home/runner/go/pkg/mod/github.com/!shopify/sarama@v1.26.4/async_producer.go:752: producer/broker/0 state change to [open] on dummy_topic/3
[kafka_output] 2021/06/02 19:48:38.319873 /home/runner/go/pkg/mod/github.com/!shopify/sarama@v1.26.4/async_producer.go:619: producer/leader/dummy_topic/3 state change to [flushing-1]
[kafka_output] 2021/06/02 19:48:38.319906 /home/runner/go/pkg/mod/github.com/!shopify/sarama@v1.26.4/async_producer.go:641: producer/leader/dummy_topic/3 state change to [normal]
```

**Comment by karimra** [comment]
Hi,

It's hard to tell what is happening from a short log snippet.
Can you enable debug and prometheus metrics under the Kafka output ? 

```yaml
prometheus-address: <addr:port> # intended address of prometheus server
outputs:
  output_name:
     type: kafka
     ....
     enable-metrics: true
     debug: true
```
The debug should enable printing kafka write errors if any,

You can curl (`curl http://<addr:port>/metrics`) the prometheus address to check if the number of `number_of_kafka_msgs_sent_fail_total` and `number_of_kafka_msgs_sent_success_total` is increasing.

**Comment by dshah2012** [comment]
Thanks @karimra yes i had a debug option globally. I see that there is no kafka error. I went through the code on this file (https://github.com/karimra/gnmic/blob/master/outputs/kafka_output/kafka_output.go) and check the message on the terminal where the logs are present there is no error.
So the prometheus-address would be the prometheus server that is already running in our environment or it is different. ?
As we have prometheus that is running in the same cluster

**Comment by karimra** [comment]
The global debug option won't enable the outputs debug, it has to be enabled for each output.

Prometheus works by pulling metrics from a target that exposes an http server, so the prometheus-address is a server address that will be started by gnmic.
You can configure the prometheus server you have running to scrape the metrics exposed by gnmic.

Nokia routers don't support `target`

**Comment by dshah2012** [comment]
Okay thanks for the clarification. So it can prometheus server address and port can be anything right?

**Comment by karimra** [comment]
yes, as long as there are no firewall rules blocking that address/port

**Comment by dshah2012** [comment]
OKay let me try and will let you know how it goes.

**Comment by dshah2012** [comment]
Actually I am using the docker image and running it in kubernetes environment. So i guess the port also should be exposed.

**Comment by dshah2012** [comment]
@karimra Just one more doubt, I see this error in collector sometimes in between, not always when we have subscription for the cisco device for the interface. 
Is it the device that is closing the connection due to the transfer of large interface payloads after running for sometime or is it the collector that is having an issue ?
This error occurs like in 20 minutes interval it disconnects and connects back again.

```
subscription cisco_interfaces rcv error: rpc error: code = Unavailable desc = transport is closing
[gnmic] 2021/06/03 02:33:06.207200 /home/runner/work/gnmic/gnmic/collector/collector.go:676: target "CR02-Cisco1", subscription cisco_interfaces rcv error: retrying in 10s
[gnmic] 2021/06/03 02:33:06.482937 /home/runner/go/pkg/mod/google.golang.org/grpc@v1.30.0/grpclog/logger.go:49: Subchannel Connectivity change to READY
[gnmic] 2021/06/03 02:33:06.482983 /home/runner/go/pkg/mod/google.golang.org/grpc@v1.30.0/grpclog/logger.go:57: pickfirstBalancer: UpdateSubConnState: 0xc000328810, {READY <nil>}
[gnmic] 2021/06/03 02:33:06.482992 /home/runner/go/pkg/mod/google.golang.org/grpc@v1.30.0/grpclog/logger.go:49: Channel Connectivity change to READY
```

**Comment by karimra** [comment]
No shell available in the docker image.
Closing the transport can be done by either the client or the server, without more information this is just a guessing game.

**Comment by dshah2012** [comment]
@karimra  In the logs i can see only that much related to this error.This is the error block that I see in the logs after the last line  of the error collector again starts receiving message  I am not sure where i look for additional information.

```
[gnmic] 2021/06/03 03:26:29.017397 /home/runner/go/pkg/mod/google.golang.org/grpc@v1.30.0/grpclog/logger.go:49: Subchannel Connectivity change to CONNECTING
[gnmic] 2021/06/03 03:26:29.017495 /home/runner/go/pkg/mod/google.golang.org/grpc@v1.30.0/grpclog/logger.go:57: pickfirstBalancer: UpdateSubConnState: 0xc000328810, {CONNECTING <nil>}
[gnmic] 2021/06/03 03:26:29.017528 /home/runner/go/pkg/mod/google.golang.org/grpc@v1.30.0/grpclog/logger.go:49: Channel Connectivity change to CONNECTING
[gnmic] 2021/06/03 03:26:29.017554 /home/runner/work/gnmic/gnmic/collector/collector.go:676: target "CR02-Cisco1", subscription cisco_interfaces rcv error: rpc error: code = Unavailable desc = transport is closing
[gnmic] 2021/06/03 03:26:29.017573 /home/runner/work/gnmic/gnmic/collector/collector.go:676: target "CR02-Cisco1", subscription cisco_interfaces rcv error: retrying in 10s
[gnmic] 2021/06/03 03:26:29.017575 /home/runner/go/pkg/mod/google.golang.org/grpc@v1.30.0/grpclog/logger.go:57: transport: loopyWriter.run returning. connection error: desc = "transport is closing"
[gnmic] 2021/06/03 03:26:29.017604 /home/runner/go/pkg/mod/google.golang.org/grpc@v1.30.0/grpclog/logger.go:49: Subchannel picks a new address "172.16.18.9:57400" to connect
[gnmic] 2021/06/03 03:26:29.036780 /home/runner/go/pkg/mod/google.golang.org/grpc@v1.30.0/grpclog/logger.go:49: Subchannel Connectivity change to READY
[gnmic] 2021/06/03 03:26:29.036801 /home/runner/go/pkg/mod/google.golang.org/grpc@v1.30.0/grpclog/logger.go:57: pickfirstBalancer: UpdateSubConnState: 0xc000328810, {READY <nil>}
[gnmic] 2021/06/03 03:26:29.036807 /home/runner/go/pkg/mod/google.golang.org/grpc@v1.30.0/grpclog/logger.go:49: Channel Connectivity change to READY
```

**Comment by karimra** [comment]
have a look at this: https://github.com/grpc/grpc-go/blob/master/README.md#the-rpc-failed-with-error-code--unavailable-desc--transport-is-closing

**Comment by dshah2012** [comment]
I think it may be an issue on the Cisco device side, for nokia the collector works fine.

**Comment by dshah2012** [comment]
Closing this ticket as this might be Vendor specific.
