### ISSUE TITLE
No prebuilt binary for M1 based Macs (darwin-arm64)

### ISSUE THREAD

**Issue by erdemkucuk** [karimra/gnmic#457]
bash -c "$(curl -sL https://get-gnmic.kmrd.dev)"
No prebuilt binary for darwin-arm64.
To build from source, go to https://github.com/karimra/gnmic
Failed to install gnmic
	For support, go to https://github.com/karimra/gnmic/issues

**Comment by karimra** [comment]
ok, thanks, I will add `darwin-arm64` to the next release

**Comment by karimra** [comment]
The latest release (v0.19.0) is available for arch arm64 on Darwin, please give the installation another try.
