### ISSUE TITLE
Add 'script' action

### ISSUE THREAD

**Issue by jbemmel** [karimra/gnmic#480]
In addition to HTTP and gNMI actions, running a local bash script (or any program) with an environment and parameters passed to it can be useful in various automation scenarios

**Comment by karimra** [comment]
makes sense, do you want to give it a shot?

**Comment by karimra** [comment]
available in release v0.21.0

**Comment by karimra** [comment]
https://gnmic.kmrd.dev/user_guide/actions/actions/#script-action
