### ISSUE TITLE
Add text template output

### ISSUE THREAD

**Issue by jbemmel** [karimra/gnmic#493]
It would be useful to have an output format that uses https://pkg.go.dev/text/template to produce arbitrary text files.

When an event or response is received, it would be passed as a parameter to the template (subject to filter expressions etc.)

**Comment by karimra** [comment]
I agree, something along these lines was suggested before as an option under file output but never happened.
I see it possible for file and msg queue type of outputs.
The subscribe response format is a bit hard to work with in a go template, this would require to change the format before passing to the template or adding few helper functions to the template.

**Comment by karimra** [comment]
available in release v0.21.0

**Comment by karimra** [comment]
https://gnmic.kmrd.dev/user_guide/actions/actions/#template-action
