### ISSUE TITLE
Issue while trying to do a set request

### ISSUE THREAD

**Issue by aikulkarni13** [karimra/gnmic#509]
Seeing the following issue while trying to do a set -
 gnmic -a <ip>:<pwd> -u <> -p <> --insecure set --update-path "openconfig-interfaces:interfaces/interface[name=*]/config" --update-value 'true'

Error:
set request failed: SetRequest failed: rpc error: code = Unknown desc = Request payload is empty

**Comment by karimra** [comment]
Can you share some logs ? ideally with `--debug` and `--print-request` flags
The error comes from the box, it means that the request is not accepted.

Looking at the path, I can assume that this an OC enabled box. 
The path `openconfig-interfaces:interfaces/interface[name=*]/config` is a container that expects this kind of format: https://github.com/openconfig/public/blob/master/release/models/interfaces/openconfig-interfaces.yang#L319

So setting the value to `true` is probably not what is expected.
