### ISSUE TITLE
Report errors on stderr, not stdout

### ISSUE THREAD

**Issue by jbemmel** [karimra/gnmic#511]
gnmic currently prints all its output on stdout, even if there is an error in a request.
One can add '--log' to log to stderr, but also without this flag errors should be reported via stderr, not mixed in with stdout

**Comment by karimra** [comment]
That shouldn't happen, which errors do you see printed to stdout ?

**Comment by jbemmel** [comment]
Unable to reproduce for now, closing until I see it again
