### ISSUE TITLE
gnmic set with `--update-file` and `--replace-file` flags are generating empty gNMI Set requests.

### ISSUE THREAD

**Issue by LeonGWang** [karimra/gnmic#557]
Empty gNMI Set requests are sent when I run `gnmic set` command while providing the `--update-file` and `--replace-file` flags.

For example:
❯ gnmic -a [address:port] -u [username] -p [password] --insecure --gzip set  \
--replace-path /acl/acl-sets \
--replace-file value.json --dry-run
{}
❯ gnmic -a [address:port] -u [username] -p [password] --insecure --gzip set  \
--update-path /acl/acl-sets \
--update-file value.json --dry-run
{}

This is the output of `gnmic version`:
❯ gnmic version
version : 0.24.0
 commit : 5472c3c
   date : 2022-03-13T19:42:32Z
 gitURL : https://github.com/karimra/gnmic
   docs : https://gnmic.kmrd.dev

**Comment by karimra** [comment]
Thanks for catching this
