### ISSUE TITLE
event-data-convert precessors dont work

### ISSUE THREAD

**Issue by LoboDCOK** [karimra/gnmic#600]
i have a last release of gnmic; but when i trie to active this event-processor, i recibe this error issues

**Error: failed reading event processors config: unknown processors type: event-data-convert**

that's ok or this is a bug?

regards

**Comment by karimra** [comment]
yep there is an issue there, will be fixed in the next release.

**Comment by karimra** [comment]
Can you give the latest version (v0.25.0) a try?

**Comment by LoboDCOK** [comment]
Great. It's working fine

Obtener Outlook para Android<https://aka.ms/ghei36>
________________________________
