### ISSUE TITLE
gnmi history extension

### ISSUE THREAD

**Issue by ksator** [karimra/gnmic#622]
Hello
I would like to use gnmic with these 2 diff use cases
https://github.com/openconfig/reference/blob/master/rpc/gnmi/gnmi-history.md#1-purpose
- retrieve data at a specific time in the past
- request all updates applied to a data tree between two specified times.

but I dont see the gnmic options for these 2 diff use cases
Is it already supported? 
Many thanks in advance for your help!

**Comment by ksator** [comment]
The gnmi client published on the GH org aristanetworks supports 3 flags for these 2 options
https://github.com/aristanetworks/goarista/blob/master/gnmi/client/client.go#L81-L89

**Comment by ksator** [comment]
Thank you @karimra !

**Comment by karimra** [comment]
welcome, please try v0.26.0 and let me know how it goes.

**Comment by ksator** [comment]
Hello @karimra 

These ones are working: 
```
gnmic -a 192.168.0.5:443 subscribe \
    --path "openconfig:/interfaces/interface/state/counters" \
    --token=`cat token.tok` --mode=once --target=spine1 \
    --skip-verify  --history-snapshot=2022-07-17T12:56:00Z
```
```
gnmic -a 192.168.0.5:443 subscribe \
    --path "openconfig:/interfaces/interface/state/counters" \
    --token=`cat token.tok` --mode=stream --target=spine1 --skip-verify\
    --history-start=2022-07-17T12:53:00Z  --history-end=2022-07-17T12:55:00Z                                                                                                                                                         ```
Thank you so much!
You can close this issue
