### ISSUE TITLE
Windows release?

### ISSUE THREAD

**Issue by Vasilich** [karimra/gnmic#630]
I am struggling to find a tool that works via gnmi protocol for windows. 
I have seen commit #194 that has removed windows compilations from release. Is there any chance to get it back in release? or chance for me to compile it somehow locally? i have no experience with Go language at all.

Thanks in advance

**Comment by karimra** [comment]
To use gnmic on Windows you have a 2 options:
1)  Install WSL2 on your windows machine and use gnmic for linux
2) Build gnmic from source:
    - Install golang18.x
    - Clone there repo: `git clone https://github.com/karimra/gnmic && cd gnmic`
    - If building on windows:
       - `go build` (a new executable `gnmic.exe` will be created in your $PWD)
     - If cross compiling on (linux/darwin) for Windows:
       - `GOOS=windows GOARCH=amd64 go build` (a new executable `gnmic.exe` will be created in your $PWD)

**Comment by Vasilich** [comment]
Thanks for the answer.
I still use WSL1, and gnmic works also there. WSL2 doesn't work with complex IT infrastructure without DHCP servers.
But it is easier for me to use version compiled for windows, and building it with your instruction was also pretty easy.
