### ISSUE TITLE
gnmic fails to receive subscribeResponse after the 1st one

### ISSUE THREAD

**Issue by hellt** [karimra/gnmic#67]
In current master the subscriptions made towards the node only print the first subscription (default stdout output)
code stops on receiving the second subscription request

**Comment by karimra** [comment]
Example of subscription created?
Content of config file ?

**Comment by hellt** [comment]
the issue was on my end with using the default subscription mode for the path /configure/system/name which was TARGET_DEFINED.
For this particular path it was ON_CHANGE, hence a single update
