### ISSUE TITLE
align configuration options between subscribe cmd flags and file-based inputs

### ISSUE THREAD

**Issue by hellt** [karimra/gnmic#73]
1. `mode` in subscription struct vs `subscription-mode` in cmd local flags
1. `stream-mode` in subscription struct vs `stream-subscription-mode` in cmd local flags

**Comment by karimra** [comment]
I will change the flags in #71

**Comment by hellt** [comment]
Done in https://github.com/karimra/gnmic/commit/2d02c5983846e143e4d5eec6491f3d32c9ad46fd
